"""SIESTA DM.InitSpin rendering and safe FDF patching."""

from __future__ import annotations

import re
import shutil
from pathlib import Path
from typing import Mapping, Sequence

from .structure import Structure


def render_dm_init_spin(
    spins: Mapping[int, float],
    *,
    method: str,
    magnetic_species: Sequence[str],
    metadata: Mapping[str, object] | None = None,
    structure: Structure | None = None,
    write_zero_spins: bool = False,
) -> str:
    """Render zero-based spin keys as one-based SIESTA atom indices."""

    metadata = dict(metadata or {})
    rows: dict[int, float] = dict(spins)
    if structure is not None and write_zero_spins:
        rows = {index: rows.get(index, 0.0) for index in range(len(structure))}
    n_up = sum(value > 0 for value in spins.values())
    n_down = sum(value < 0 for value in spins.values())
    header = [
        "# Generated by siesta-afm",
        f"# Method: {method}",
        f"# Magnetic species: {' '.join(magnetic_species)}",
    ]
    preferred = [
        ("axis", "Axis"),
        ("plane", "Plane"),
        ("cutoff", "Neighbor cutoff"),
        ("q_vector", "Propagation vector"),
        ("layer_tolerance", "Layer tolerance"),
        ("heuristic", "Heuristic"),
    ]
    for key, label in preferred:
        if key in metadata:
            header.append(f"# {label}: {_format_metadata(metadata[key])}")
    magnitudes = sorted({round(abs(value), 12) for value in spins.values() if value})
    if len(magnitudes) == 1:
        header.append(f"# Moment magnitude: {magnitudes[0]:g}")
    elif magnitudes:
        header.append("# Moment magnitudes: " + ", ".join(f"{v:g}" for v in magnitudes))
    header.extend(
        [
            f"# Number of spin-up atoms: {n_up}",
            f"# Number of spin-down atoms: {n_down}",
            "Spin polarized",
            "",
            "%block DM.InitSpin",
        ]
    )
    for index in sorted(rows):
        header.append(f"{index + 1:6d} {rows[index]:12.6f}")
    header.append("%endblock DM.InitSpin")
    return "\n".join(header) + "\n"


def _format_metadata(value: object) -> str:
    if isinstance(value, (list, tuple)):
        return " ".join(str(item) for item in value)
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


_DM_INIT_SPIN_LABEL_RE = r"[._-]*".join("DMInitSpin")
_SPIN_BLOCK_RE = re.compile(
    rf"(?ims)^[ \t]*%block[ \t]+{_DM_INIT_SPIN_LABEL_RE}[ \t]*$.*?"
    rf"^[ \t]*%endblock(?:[ \t]+{_DM_INIT_SPIN_LABEL_RE})?[ \t]*(?:\r?\n)?"
)


def _normalize_fdf_label(value: str) -> str:
    return re.sub(r"[._-]", "", value).lower()


def _parse_fdf_logical(value: str) -> bool | None:
    """Parse common FDF logical spellings, including dotted Fortran forms."""

    normalized = _normalize_fdf_label(value)
    if normalized in {"true", "t", "yes", "y", "1", "on"}:
        return True
    if normalized in {"false", "f", "no", "n", "0", "off"}:
        return False
    return None


def _spin_control(line: str) -> tuple[str, str] | None:
    """Classify legacy and modern FDF spin-control keyword lines."""

    code = re.split(r"[#!]", line, maxsplit=1)[0].strip()
    fields = code.split()
    if len(fields) < 2 or fields[0].startswith("%"):
        return None
    keyword = _normalize_fdf_label(fields[0])
    if keyword == "spinpolarized":
        return "legacy-polarized", fields[1]
    if keyword in {"noncollinearspin", "spinorbit"}:
        return f"legacy-{keyword}", fields[1]
    if keyword == "spin":
        return "modern", _normalize_fdf_label(fields[1])
    return None


def _patch_spin_control(input_text: str) -> str:
    lines = input_text.splitlines()
    controls = [(index, _spin_control(line)) for index, line in enumerate(lines)]
    controls = [(index, control) for index, control in controls if control is not None]
    incompatible = {
        "noncollinear",
        "noncolinear",
        "spinorbit",
        "spinorbitonsite",
    }
    for _, (kind, value) in controls:
        if kind.startswith("legacy-"):
            enabled = _parse_fdf_logical(value)
            if enabled is None:
                raise ValueError(
                    f"unrecognized FDF logical value {value!r} for "
                    f"{kind.removeprefix('legacy-')}"
                )
            if kind in {"legacy-noncollinearspin", "legacy-spinorbit"} and enabled:
                keyword = kind.removeprefix("legacy-")
                raise ValueError(
                    "cannot patch collinear DM.InitSpin into an FDF input using "
                    f"enabled legacy '{keyword}'; use a collinear "
                    "'Spin polarized' calculation"
                )
        elif value in incompatible or value.startswith("spinorbit"):
            raise ValueError(
                "cannot patch collinear DM.InitSpin into an FDF input using "
                f"'Spin {value}'; use a collinear 'Spin polarized' calculation"
            )
    if controls:
        first_index = controls[0][0]
        indent = re.match(r"^\s*", lines[first_index]).group(0)  # type: ignore[union-attr]
        lines[first_index] = f"{indent}Spin polarized"
        for index, _ in reversed(controls[1:]):
            del lines[index]
        return "\n".join(lines) + ("\n" if input_text.endswith(("\n", "\r")) else "")
    return input_text.rstrip() + "\n\nSpin polarized\n"


def patch_fdf_text(input_text: str, spin_text: str) -> str:
    """Replace/insert spin controls and DM.InitSpin without touching atom data."""

    block_match = _SPIN_BLOCK_RE.search(spin_text)
    if not block_match:
        raise ValueError("spin file does not contain a DM.InitSpin block")
    block = block_match.group(0).strip() + "\n"

    patched = _patch_spin_control(input_text)

    if _SPIN_BLOCK_RE.search(patched):
        patched = _SPIN_BLOCK_RE.sub(block + "\n", patched, count=1)
    else:
        patched = patched.rstrip() + "\n\n" + block
    return patched.rstrip() + "\n"


def patch_fdf_file(
    input_path: str | Path,
    spin_path: str | Path,
    *,
    output_path: str | Path | None = None,
    in_place: bool = False,
    backup: bool = False,
) -> Path:
    source = Path(input_path)
    spin_source = Path(spin_path)
    if (
        in_place
        and output_path is not None
        and Path(output_path).resolve() != source.resolve()
    ):
        raise ValueError("--in-place cannot be combined with a different --output")
    if not in_place and output_path is None:
        raise ValueError("patch requires --output unless --in-place is specified")
    destination = source if in_place else Path(output_path)  # type: ignore[arg-type]
    if destination.resolve() == source.resolve() and not in_place:
        raise ValueError("refusing to overwrite input without --in-place")
    patched = patch_fdf_text(
        source.read_text(encoding="utf-8-sig"),
        spin_source.read_text(encoding="utf-8-sig"),
    )
    if backup:
        shutil.copy2(source, Path(str(source) + ".bak"))
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(patched, encoding="utf-8")
    return destination
